# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_merge_resolve_type <- function(df_to_merge) {
    .Call(`_flexlsx_cpp_merge_resolve_type`, df_to_merge)
}

